"""Write markdown codebooks for generated outputs.

Each pipeline or analysis script documents the files it writes by calling
`update_codebook` with variable definitions. A codebook.md can hold sections
from several scripts (e.g., output/codebook.md), so sections are delimited
with HTML comment markers and replaced in place on rerun.
"""

from pathlib import Path

HEADER = (
    "# Codebook\n\n"
    "Variable definitions for the generated files in this directory. This "
    "file is written by the pipeline scripts; edit the definitions in the "
    "generating script, not here.\n"
)


def _render_section(
    section: str,
    title: str,
    files: list[dict],
    intro: str | None,
    source: str | None,
) -> str:
    lines = [f"<!-- BEGIN CODEBOOK SECTION: {section} -->", f"## {title}", ""]
    if source:
        lines += [f"Generated by `{source}`.", ""]
    if intro:
        lines += [intro, ""]
    for spec in files:
        lines += [f"### `{spec['name']}`", "", spec["description"], ""]
        lines += ["| Variable | Definition |", "| --- | --- |"]
        lines += [
            f"| `{name}` | {definition} |" for name, definition in spec["columns"]
        ]
        lines += [""]
    lines.append(f"<!-- END CODEBOOK SECTION: {section} -->")
    return "\n".join(lines)


def update_codebook(
    path: Path,
    section: str,
    title: str,
    files: list[dict],
    intro: str | None = None,
    source: str | None = None,
) -> None:
    """Create or replace one marker-delimited section of a codebook file.

    Parameters
    ----------
    path : codebook.md location.
    section : stable machine name used in the section markers.
    title : section heading shown in the codebook.
    files : list of {"name", "description", "columns"} dicts, where columns
        is a list of (variable, definition) tuples.
    intro : optional prose shown before the file tables.
    source : the generating script, shown under the heading.
    """
    rendered = _render_section(section, title, files, intro, source)
    begin = f"<!-- BEGIN CODEBOOK SECTION: {section} -->"
    end = f"<!-- END CODEBOOK SECTION: {section} -->"

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        text = path.read_text()
    else:
        text = HEADER

    if begin in text and end in text:
        head, rest = text.split(begin, 1)
        _, tail = rest.split(end, 1)
        text = head + rendered + tail
    else:
        text = text.rstrip("\n") + "\n\n" + rendered + "\n"

    path.write_text(text)
